=== x-govuk/govuk-services-list/data/service.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./service.schema.json",
  "title": "GOV.UK service data",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "organisation", "phase"],
  "properties": {
    "name": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "description": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "synonyms": {
      "$ref": "#/$defs/nonEmptyStringArray"
    },
    "organisation": {
      "oneOf": [
        {
          "$ref": "#/$defs/nonEmptyString"
        },
        {
          "$ref": "#/$defs/nonEmptyStringArray"
        }
      ]
    },
    "theme": {
      "enum": [
        "Benefits",
        "Births, deaths, marriages and care",
        "Business and self-employed",
        "Childcare and parenting",
        "Citizenship and living in the UK",
        "Coronavirus (COVID-19)",
        "Crime, justice and the law",
        "Driving and transport",
        "Education and learning",
        "Employing people",
        "Environment and countryside",
        "Government internal",
        "Health",
        "Housing and local services",
        "Money and tax",
        "Passports, travel and living abroad",
        "Transport",
        "Visas and immigration",
        "Working, jobs and pensions"
      ]
    },
    "phase": {
      "enum": ["Discovery", "Alpha", "Beta", "Live", "Retired", "Unknown"]
    },
    "phase_modifier": {
      "enum": ["Private", "Public"]
    },
    "facing": {
      "enum": ["internal"]
    },
    "liveService": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "startPage": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "platform": {
      "oneOf": [
        {
          "enum": ["app", "web"]
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "enum": ["app", "web"]
          }
        }
      ]
    },
    "prototype": {
      "$ref": "#/$defs/uriString"
    },
    "sourceCode": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["href", "text"],
        "properties": {
          "href": {
            "$ref": "#/$defs/uriString"
          },
          "text": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "timeline": {
      "type": "object",
      "additionalProperties": false,
      "required": ["items"],
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["label", "date"],
            "properties": {
              "label": {
                "$ref": "#/$defs/nonEmptyString"
              },
              "date": {
                "type": "string",
                "format": "date"
              },
              "links": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": ["href", "text"],
                  "properties": {
                    "href": {
                      "$ref": "#/$defs/uriString"
                    },
                    "text": {
                      "$ref": "#/$defs/nonEmptyString"
                    },
                    "visuallyHiddenText": {
                      "$ref": "#/$defs/nonEmptyString"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "$defs": {
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "nonEmptyStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    },
    "uriStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/uriString"
      }
    }
  }
}

=== x-govuk/govuk-services-list/data/services/import-products-animals-food-feed.json
{
  "name": "Import of products, animals, food and feed service",
  "synonyms": ["Import of products, animals, food and feed system (IPAFFS)"],
  "description": "Use IPAFFS to notify enforcement authorities about imports to Great Britain.",
  "theme": "Business and self-employed",
  "organisation": "Department for Environment, Food & Rural Affairs",
  "phase": "Live",
  "startPage": "https://www.gov.uk/guidance/import-of-products-animals-food-and-feed-system",
  "liveService": "https://import-products-animals-food-feed.service.gov.uk/notification/prd/protected/notifications",
  "timeline": {
    "items": [
      {
        "label": "Did not pass alpha assessment",
        "date": "2021-07-13",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/import-of-products-animals-food-and-feed-system-ipaffs-plant-journey",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      }
    ]
  }
}

=== x-govuk/govuk-services-list/data/services/view-designs-journal.json
{
  "name": "View designs journal",
  "description": "View designs registered in the designs journal from the last 25 years",
  "organisation": "Intellectual Property Office",
  "theme": "Business and self-employed",
  "phase": "Beta",
  "liveService": "https://www.registered-design.service.gov.uk/view",
  "startPage": "https://www.gov.uk/check-the-design-journal",
  "synonyms": ["Check the designs journal"]
}

=== x-govuk/govuk-services-list/data/services/calculate-teacher-pay.json
{
  "name": "Calculate teacher pay",
  "description": "Calculate teacher pay following the 2023 pay award",
  "organisation": "Department for Education",
  "theme": "Education and learning",
  "phase": "Beta",
  "liveService": "https://calculate-teacher-pay.education.gov.uk",
  "sourceCode": [
    {
      "text": "Source code",
      "href": "https://github.com/DFE-Digital/teacher-pay-calculator"
    }
  ]
}

=== x-govuk/govuk-services-list/data/services/mot-testing.json
{
  "name": "MOT testing service",
  "synonyms": [
    "Record MOT test results"
  ],
  "description": "Use this service if you’re an MOT tester and you need to record results of MOTs you carry out, print MOT certificates or buy test slots and check your test station’s balance.",
  "theme": "Driving and transport",
  "organisation": "Driver and Vehicle Standards Agency",
  "phase": "Unknown",
  "liveService": "https://www.mot-testing.service.gov.uk/",
  "startPage": "https://www.gov.uk/mot-testing-service",
  "timeline": {
    "items": [
      {
        "label": "Passed live reassessment",
        "date": "2018-10-30",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/record-mot-test-results-live-reassessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for live reassessment"
          }
        ]
      }
    ]
  },
  "sourceCode": [
    {
      "text": "Source code",
      "href": "https://github.com/dvsa/mot"
    }
  ]
}

=== x-govuk/govuk-services-list/data/services/apply-for-an-export-certificate.json
{
  "name": "Apply for an export certificate",
  "synonyms": ["Apply for a Certificate of Free Sale"],
  "description": "Use this service to apply for an export certificate",
  "theme": "Business and self-employed",
  "organisation": ["Department for Business and Trade"],
  "phase": "Beta",
  "liveService": "https://apply-for-an-export-certificate.service.gov.uk/login-start/",
  "startPage": "https://www.gov.uk/guidance/apply-for-an-export-certificate",
  "tags": ["GOV.UK One Login"]
}

=== x-govuk/govuk-services-list/data/services/gambling-tax.json
{
  "name": "Register for gambling tax",
  "description": "Register for General Betting Duty (GBD), Pool Betting Duty (PBD) or Remote Gaming Duty (RGD).",
  "theme": "Money and tax",
  "organisation": "HM Revenue and Customs",
  "phase": "Beta",
  "startPage": [
    "https://www.gov.uk/register-pay-gambling-tax",
    "https://www.gov.uk/file-gambling-tax-return"
  ],
  "liveService": "https://www.tax.service.gov.uk/gg/sign-in?continue=/business-account/&origin=GAMBLING-frontend",
  "synonyms": [
    "File your gambling tax return"
  ]
}

=== x-govuk/govuk-services-list/data/services/view-your-education-data.json
{
  "name": "View your education data",
  "description": "This service provides analytical insights to support business intelligence and better decision making.",
  "organisation": "Department for Education",
  "theme": "Education and learning",
  "phase": "Beta",
  "liveService": "https://viewyourdata.education.gov.uk",
  "startPage": "https://www.gov.uk/government/publications/16-to-19-data-and-management-information-mi-reports/accessing-the-view-your-education-data-portal-vyed"
}

=== x-govuk/govuk-services-list/data/services/register-charity-hmrc.json
{
  "name": "Register your charity’s details with HMRC",
  "synonyms": ["Get recognition from HMRC for your charity"],
  "description": "You can register your charity’s details with HM Revenue and Customs (HMRC) to get tax back on things like Gift Aid donations.",
  "organisation": "HM Revenue and Customs",
  "theme": "Money and tax",
  "phase": "Beta",
  "liveService": "https://www.tax.service.gov.uk/register-charity-hmrc/check-eligibility/register-the-charity",
  "startPage": "https://www.gov.uk/charity-recognition-hmrc"
}
