=== x-govuk/govuk-services-list/data/service.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./service.schema.json",
  "title": "GOV.UK service data",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "organisation", "phase"],
  "properties": {
    "name": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "description": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "synonyms": {
      "$ref": "#/$defs/nonEmptyStringArray"
    },
    "organisation": {
      "oneOf": [
        {
          "$ref": "#/$defs/nonEmptyString"
        },
        {
          "$ref": "#/$defs/nonEmptyStringArray"
        }
      ]
    },
    "theme": {
      "enum": [
        "Benefits",
        "Births, deaths, marriages and care",
        "Business and self-employed",
        "Childcare and parenting",
        "Citizenship and living in the UK",
        "Coronavirus (COVID-19)",
        "Crime, justice and the law",
        "Driving and transport",
        "Education and learning",
        "Employing people",
        "Environment and countryside",
        "Government internal",
        "Health",
        "Housing and local services",
        "Money and tax",
        "Passports, travel and living abroad",
        "Transport",
        "Visas and immigration",
        "Working, jobs and pensions"
      ]
    },
    "phase": {
      "enum": ["Discovery", "Alpha", "Beta", "Live", "Retired", "Unknown"]
    },
    "phase_modifier": {
      "enum": ["Private", "Public"]
    },
    "facing": {
      "enum": ["internal"]
    },
    "liveService": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "startPage": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "platform": {
      "oneOf": [
        {
          "enum": ["app", "web"]
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "enum": ["app", "web"]
          }
        }
      ]
    },
    "prototype": {
      "$ref": "#/$defs/uriString"
    },
    "sourceCode": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["href", "text"],
        "properties": {
          "href": {
            "$ref": "#/$defs/uriString"
          },
          "text": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "timeline": {
      "type": "object",
      "additionalProperties": false,
      "required": ["items"],
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["label", "date"],
            "properties": {
              "label": {
                "$ref": "#/$defs/nonEmptyString"
              },
              "date": {
                "type": "string",
                "format": "date"
              },
              "links": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": ["href", "text"],
                  "properties": {
                    "href": {
                      "$ref": "#/$defs/uriString"
                    },
                    "text": {
                      "$ref": "#/$defs/nonEmptyString"
                    },
                    "visuallyHiddenText": {
                      "$ref": "#/$defs/nonEmptyString"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "$defs": {
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "nonEmptyStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    },
    "uriStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/uriString"
      }
    }
  }
}

=== x-govuk/govuk-services-list/data/services/plan-shared-parental-leave.json
{
  "name": "Plan shared parental leave and pay",
  "description": "Plan how and when you and your partner take Shared Parental Leave. Find out how much Statutory Shared Parental Pay you would get and when to give notice.",
  "organisation": "Department for Business and Trade",
  "theme": "Childcare and parenting",
  "phase": "Beta",
  "liveService": "https://www.plan-shared-parental-leave.service.gov.uk/",
  "startPage": "https://www.gov.uk/plan-shared-parental-leave-pay",
  "synonyms": ["Plan your Shared Parental Leave and Pay"]
}

=== x-govuk/govuk-services-list/data/services/check-council-tax-band.json
{
  "name": "Check and challenge your Council Tax band",
  "synonyms": ["Check your Council Tax band"],
  "description": "Find out the Council Tax band for a home in England or Wales by looking up its address or postcode. You can also use this service to challenge your Council Tax band if you think itâ€™s wrong.",
  "organisation": "HM Revenue and Customs",
  "theme": "Money and tax",
  "phase": "Beta",
  "liveService": "https://www.tax.service.gov.uk/check-council-tax-band/search",
  "startPage": "https://www.gov.uk/council-tax-bands"
}

=== x-govuk/govuk-services-list/data/services/view-health-screening-recommendations.json
{
  "name": "UK National Screening Committee",
  "description": "This list summarises whether population screening is currently recommended for a condition or not, and if it is open to public comments at this time.",
  "organisation": "Department for Health and Social Care",
  "theme": "Health",
  "phase": "Beta",
  "liveService": "https://view-health-screening-recommendations.service.gov.uk",
  "platform": "web"
}

=== x-govuk/govuk-services-list/data/services/flood-warning-info.json
{
  "name": "Check for flooding",
  "description": "Use this service to check current flood warnings or alerts, river, sea, groundwater and rainfall levels and flood risk in the next 5 days.",
  "theme": "Environment and countryside",
  "organisation": "Environment Agency",
  "phase": "Beta",
  "startPage": "https://www.gov.uk/check-flooding",
  "liveService": "https://check-for-flooding.service.gov.uk/",
  "sourceCode": [
    {
      "text": "Source code",
      "href": "https://github.com/DEFRA/flood-app"
    }
  ],
  "synonyms": ["Check for flooding "]
}

=== x-govuk/govuk-services-list/app/services/register-short-term-let.json
{
  "name": "Register a property as a short term let",
  "description": "This service aims to solve the problem of a lack of reliable insight around short-term lets in England.",
  "organisation": "Department for Culture, Media and Sport",
  "theme": "Housing and local services",
  "phase": "Alpha",
  "timeline": {
    "items": [
      {
        "label": "Assessed as green at at alpha assessment",
        "date": "2024-09-25",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/register-a-property-as-a-short-term-let-alpha-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      },
      {
        "label": "Guidance published",
        "date": "2024-02-14",
        "links": [
          {
            "href": "https://www.gov.uk/guidance/delivering-a-registration-scheme-for-short-term-lets",
            "text": "Delivering a registration scheme for short-term lets"
          }
        ]
      }
    ]
  }
}

=== x-govuk/govuk-services-list/data/services/birth-abroad-payment.json
{
  "name": "Register a birth abroad",
  "synonyms": [
    "Payment to register a birth abroad",
    "Pay to register a birth abroad"
  ],
  "description": "Pay to register the birth of a British national abroad.",
  "organisation": "Foreign, Commonwealth & Development Office",
  "theme": "Births, deaths, marriages and care",
  "phase": "Beta",
  "startPage": [
    "https://www.gov.uk/register-a-birth",
    "https://www.gov.uk/register-birth-abroad"
  ],
  "liveService": "https://register-a-birth-abroad.service.gov.uk/"
}

=== x-govuk/govuk-services-list/data/services/skillsforcareers.json
{
  "name": "Skills for careers",
  "description": "You can get career ideas and browse your training options at your own pace. Try to consider whatâ€™s possible now or for the future.",
  "organisation": "Department for Education",
  "theme": "Education and learning",
  "phase": "Beta",
  "liveService": "https://www.skillsforcareers.education.gov.uk"
}

=== x-govuk/govuk-services-list/data/services/get-help-arranging-child-maintenance.json
{
  "name": "Get help arranging child maintenance",
  "synonyms": [
    "Apply for help arranging Child Maintenance"
  ],
  "description": "This service will give you information about the different options available to make a child maintenance arrangement.",
  "organisation": "Department for Work and Pensions",
  "theme": "Childcare and parenting",
  "phase": "Beta",
  "liveService": "https://child-maintenance.service.gov.uk/get-help-arranging-child-maintenance/",
  "startPage": "https://www.gov.uk/child-maintenance-service/how-to-apply",
  "timeline": {
    "items": [
      {
        "label": "Passed alpha assessment",
        "date": "2019-10-24",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/apply-for-help-arranging-child-maintenance-alpha-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      },
      {
        "label": "Passed second alpha assessment",
        "date": "2021-06-10",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/get-help-arranging-child-maintenance-alpha-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for second alpha assessment"
          }
        ]
      },
      {
        "label": "Passed beta assessment",
        "date": "2020-12-03",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/apply-for-help-arranging-child-maintenance-beta-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for beta assessment"
          }
        ]
      },
      {
        "label": "Did not pass beta assessment",
        "date": "2022-07-20",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/get-help-arranging-child-maintenance",
            "text": "Service assessment report",
            "visuallyHiddenText": "for beta assessment"
          }
        ]
      }
    ]
  }
}
