=== x-govuk/govuk-services-list/data/service.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./service.schema.json",
  "title": "GOV.UK service data",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "organisation", "phase"],
  "properties": {
    "name": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "description": {
      "$ref": "#/$defs/nonEmptyString"
    },
    "synonyms": {
      "$ref": "#/$defs/nonEmptyStringArray"
    },
    "organisation": {
      "oneOf": [
        {
          "$ref": "#/$defs/nonEmptyString"
        },
        {
          "$ref": "#/$defs/nonEmptyStringArray"
        }
      ]
    },
    "theme": {
      "enum": [
        "Benefits",
        "Births, deaths, marriages and care",
        "Business and self-employed",
        "Childcare and parenting",
        "Citizenship and living in the UK",
        "Coronavirus (COVID-19)",
        "Crime, justice and the law",
        "Driving and transport",
        "Education and learning",
        "Employing people",
        "Environment and countryside",
        "Government internal",
        "Health",
        "Housing and local services",
        "Money and tax",
        "Passports, travel and living abroad",
        "Transport",
        "Visas and immigration",
        "Working, jobs and pensions"
      ]
    },
    "phase": {
      "enum": ["Discovery", "Alpha", "Beta", "Live", "Retired", "Unknown"]
    },
    "phase_modifier": {
      "enum": ["Private", "Public"]
    },
    "facing": {
      "enum": ["internal"]
    },
    "liveService": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "startPage": {
      "oneOf": [
        {
          "$ref": "#/$defs/uriString"
        },
        {
          "$ref": "#/$defs/uriStringArray"
        }
      ]
    },
    "platform": {
      "oneOf": [
        {
          "enum": ["app", "web"]
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "enum": ["app", "web"]
          }
        }
      ]
    },
    "prototype": {
      "$ref": "#/$defs/uriString"
    },
    "sourceCode": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["href", "text"],
        "properties": {
          "href": {
            "$ref": "#/$defs/uriString"
          },
          "text": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "timeline": {
      "type": "object",
      "additionalProperties": false,
      "required": ["items"],
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["label", "date"],
            "properties": {
              "label": {
                "$ref": "#/$defs/nonEmptyString"
              },
              "date": {
                "type": "string",
                "format": "date"
              },
              "links": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": ["href", "text"],
                  "properties": {
                    "href": {
                      "$ref": "#/$defs/uriString"
                    },
                    "text": {
                      "$ref": "#/$defs/nonEmptyString"
                    },
                    "visuallyHiddenText": {
                      "$ref": "#/$defs/nonEmptyString"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "$defs": {
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "nonEmptyStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    },
    "uriStringArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/uriString"
      }
    }
  }
}

=== x-govuk/govuk-services-list/data/services/check-international-trade-barriers.json
{
  "name": "Check International Trade Barriers",
  "description": "Find information about potential barriers to exporting goods, providing services or investing in foreign countries",
  "organisation": "Department for International Trade",
  "theme": "Business and self-employed",
  "phase": "Beta",
  "liveService": "https://check-international-trade-barriers.service.gov.uk/",
  "startPage": "https://www.gov.uk/barriers-trading-investing-abroad",
  "synonyms": ["Check for barriers to trading and investing abroad"]
}

=== x-govuk/govuk-services-list/data/services/plastic-packaging-tax.json
{
  "name": "Plastic packaging tax",
  "synonyms": ["Register for Plastic Packaging Tax"],
  "description": "Entities that import or produce plastic packaging will soon be liable for a tax. This service allows users to register, fill in returns and pay the tax due.",
  "organisation": "HM Revenue and Customs",
  "theme": "Business and self-employed",
  "phase": "Beta",
  "startPage": "https://www.gov.uk/guidance/register-for-plastic-packaging-tax",
  "liveService": "https://www.tax.service.gov.uk/register-for-plastic-packaging-tax/start-registration",
  "timeline": {
    "items": [
      {
        "label": "Passed alpha assessment",
        "date": "2021-09-24",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/plastic-packaging-tax",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      },
      {
        "label": "Passed beta assessment",
        "date": "2022-03-08",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/plastic-packaging-tax-beta-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for beta assessment"
          }
        ]
      }
    ]
  }
}

=== x-govuk/govuk-services-list/data/services/visas-and-immigration.json
{
  "name": "Apply for a Standard Visitor visa",
  "synonyms": [
    "Visas",
    "Apply for an EU Settlement Scheme travel permit to return to the UK"
  ],
  "description": "If you need a visa, you must apply online before you travel to the UK.",
  "theme": "Visas and immigration",
  "organisation": ["Home Office", "UK Visas and Immigration"],
  "phase": "Beta",
  "startPage": [
    "https://www.gov.uk/standard-visitor-visa/apply",
    "https://www.gov.uk/euss-travel-permit"
  ],
  "liveService": "https://visas-immigration.service.gov.uk/apply-visa-type/visit",
  "tags": ["Top 75", "Original 25 exemplars"],
  "timeline": {
    "items": [
      {
        "label": "Passed beta reassessment",
        "date": "2014-06-20",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/visas-beta-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha reassessment"
          }
        ]
      },
      {
        "label": "Did not pass beta assessment",
        "date": "2014-06-03",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/visas-beta-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      }
    ]
  }
}

=== x-govuk/govuk-services-list/data/services/findapprenticeshiptraining.json
{
  "name": "Find apprenticeship training for your apprentice",
  "synonyms": ["Find apprenticeship training if you're an employer"],
  "description": "If you’re an employer, you can find training for your apprentices.",
  "theme": "Education and learning",
  "organisation": ["Department for Education"],
  "phase": "Beta",
  "startPage": "https://www.gov.uk/employers-find-apprenticeship-training",
  "liveService": "https://findapprenticeshiptraining.apprenticeships.education.gov.uk/courses",
  "sourceCode": [
    {
      "text": "Source code",
      "href": "https://github.com/SkillsFundingAgency/das-findapprenticeshiptraining"
    }
  ]
}

=== x-govuk/govuk-services-list/data/services/change-your-driving-test.json
{
  "name": "Change your driving test",
  "description": "Use this service to find an earlier driving test, move your driving test to a later date or change which test centre you take your test at.",
  "theme": "Driving and transport",
  "organisation": "Driver and Vehicle Standards Agency",
  "phase": "Beta",
  "liveService": "https://driverpracticaltest.dvsa.gov.uk/login",
  "startPage": [
    "https://www.gov.uk/change-driving-test",
    "https://www.gov.uk/check-driving-test",
    "https://www.gov.uk/cancel-driving-test"
  ],
  "synonyms": [
    "Change your driving test appointment",
    "Check your driving test appointment details",
    "Cancel your driving test"
  ]
}

=== x-govuk/govuk-services-list/data/services/licencing-international-trade.json
{
  "name": "Licensing for International Trade",
  "description": "The new Licensing for International Trade and Enterprise service, part of the One Government at the Border programme, will provide a single service for import and export permissions across multiple departments. The service is currently focussed on the licensing of controlled (military and dualÂ­-use) goods, subject to the Export Control Act 2002.",
  "theme": "Business and self-employed",
  "organisation": "Department for Business and Trade",
  "phase": "Alpha",
  "timeline": {
    "items": [
      {
        "label": "Passed alpha assessment",
        "date": "2017-06-28",
        "links": [
          {
            "href": "https://www.gov.uk/service-standard-reports/licensing-for-international-trade-alpha-assessment",
            "text": "Service assessment report",
            "visuallyHiddenText": " for alpha assessment"
          }
        ]
      },
      {
        "label": "Did not pass alpha assessment",
        "date": "2017-05-27"
      }
    ]
  }
}

=== x-govuk/govuk-services-list/data/services/penaltynotice.json
{
  "name": "Penalty Notice Portal",
  "description": "The Penalty Notice Portal allows you to pay your Penalty Notice.",
  "theme": "Crime, justice and the law",
  "organisation": "Home Office",
  "phase": "Alpha",
  "startPage": "https://www.gov.uk/parking-tickets",
  "liveService": "https://penaltynotice.homeoffice.gov.uk"
}

=== x-govuk/govuk-services-list/data/services/replace-mot-certificate.json
{
  "name": "Replace MOT certificate",
  "description": "You can get a replacement MOT certificate online if you’ve lost or damaged the original.",
  "theme": "Driving and transport",
  "organisation": "Driver and Vehicle Standards Agency",
  "phase": "Beta",
  "liveService": "https://www.check-mot.service.gov.uk/?skipResults=true",
  "startPage": "https://www.gov.uk/replacing-lost-damaged-mot-certificate",
  "synonyms": [
    "Replace a lost or damaged MOT certificate"
  ]
}
